import { supabase } from './supabase'

export type AppointmentType = { id: number, name: string, duration_minutes: number, interval_minutes: number, active: boolean, professional_id: number | null, professionals: { name: string } | null }
export type WorkingHour = { id: number, weekday: number, start_time: string, end_time: string, professional_id: number | null, professionals: { name: string } | null }

const requireClient = () => { if (!supabase) throw new Error('Configure o Supabase antes de continuar.'); return supabase }
export async function listAppointmentTypes(clinicId: number) { const { data, error } = await requireClient().from('appointment_types').select('id, name, duration_minutes, interval_minutes, active, professional_id, professionals(name)').eq('clinic_id', clinicId).order('name'); if (error) throw error; return (data ?? []).map(item => ({ ...item, professionals: Array.isArray(item.professionals) ? item.professionals[0] ?? null : item.professionals })) as AppointmentType[] }
export async function createAppointmentType(clinicId: number, input: { professionalId: number, name: string, duration: number, interval: number }) { const { error } = await requireClient().from('appointment_types').insert({ clinic_id: clinicId, professional_id: input.professionalId, name: input.name.trim(), duration_minutes: input.duration, interval_minutes: input.interval }); if (error) throw error }
export async function setAppointmentTypeActive(id: number, active: boolean) { const { error } = await requireClient().from('appointment_types').update({ active }).eq('id', id); if (error) throw error }
export async function deleteAppointmentType(id: number) { const { error } = await requireClient().from('appointment_types').delete().eq('id', id); if (error) throw error }
export async function listWorkingHours(clinicId: number) { const { data, error } = await requireClient().from('working_hours').select('id, weekday, start_time, end_time, professional_id, professionals(name)').eq('clinic_id', clinicId).order('weekday').order('start_time'); if (error) throw error; return (data ?? []).map(item => ({ ...item, professionals: Array.isArray(item.professionals) ? item.professionals[0] ?? null : item.professionals })) as WorkingHour[] }
export async function createWorkingHour(clinicId: number, input: { professionalId: number | null, weekday: number, startTime: string, endTime: string }) { const { error } = await requireClient().from('working_hours').insert({ clinic_id: clinicId, professional_id: input.professionalId, weekday: input.weekday, start_time: input.startTime, end_time: input.endTime }); if (error) throw error }
export async function deleteWorkingHour(id: number) { const { error } = await requireClient().from('working_hours').delete().eq('id', id); if (error) throw error }
