import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Armchair, BriefcaseMedical, DoorOpen, MailPlus, UserRoundPlus, Users } from 'lucide-react'
import { inviteMember, listMembers, listProfessionals, listResources, saveProfessional, saveResource, setMemberActive, setProfessionalActive, setResourceActive, type OrganizationMember } from '../lib/organizationTeam'

export function OrganizationTeamSection({ clinicId, enabled }: { clinicId: number, enabled: boolean }) {
  const client = useQueryClient()
  const [notice, setNotice] = useState('')
  const [invite, setInvite] = useState({ name: '', email: '', temporaryPassword: '', role: 'secretary' as 'secretary' | 'professional', specialty: '' })
  const [professional, setProfessional] = useState({ name: '', specialty: '' })
  const [resource, setResource] = useState({ name: '', resourceType: '' })
  const members = useQuery({ queryKey: ['members', clinicId], queryFn: () => listMembers(clinicId), enabled })
  const professionals = useQuery({ queryKey: ['professionals', clinicId], queryFn: () => listProfessionals(clinicId), enabled })
  const resources = useQuery({ queryKey: ['resources', clinicId], queryFn: () => listResources(clinicId), enabled })
  const refresh = () => { client.invalidateQueries({ queryKey: ['members', clinicId] }); client.invalidateQueries({ queryKey: ['professionals', clinicId] }); client.invalidateQueries({ queryKey: ['resources', clinicId] }) }
  const reportError = (error: Error) => setNotice(`Erro: ${translateError(error.message)}`)
  const inviteMutation = useMutation({ mutationFn: () => inviteMember(clinicId, invite), onSuccess: () => { setInvite({ name: '', email: '', temporaryPassword: '', role: 'secretary', specialty: '' }); setNotice('Usuário cadastrado com sucesso.'); refresh() }, onError: reportError })
  const professionalMutation = useMutation({ mutationFn: () => saveProfessional(clinicId, professional), onSuccess: () => { setProfessional({ name: '', specialty: '' }); setNotice('Profissional cadastrado com sucesso.'); refresh() }, onError: reportError })
  const resourceMutation = useMutation({ mutationFn: () => saveResource(clinicId, resource), onSuccess: () => { setResource({ name: '', resourceType: '' }); setNotice('Recurso cadastrado com sucesso.'); refresh() }, onError: reportError })
  const toggleMember = useMutation({ mutationFn: ({ id, active }: { id: number, active: boolean }) => setMemberActive(clinicId, id, active), onSuccess: refresh, onError: reportError })
  const toggleProfessional = useMutation({ mutationFn: ({ id, active }: { id: number, active: boolean }) => setProfessionalActive(id, active), onSuccess: refresh, onError: reportError })
  const toggleResource = useMutation({ mutationFn: ({ id, active }: { id: number, active: boolean }) => setResourceActive(id, active), onSuccess: refresh, onError: reportError })
  if (!enabled) return null
  const submit = (event: FormEvent, action: () => void) => { event.preventDefault(); setNotice(''); action() }
  return <section className="mt-8 grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><Title icon={<Users />} title="Usuários com acesso" text="Convide secretárias ou profissionais para utilizar o painel." /><form onSubmit={event => submit(event, inviteMutation.mutate)} className="mt-5 grid gap-3 sm:grid-cols-2"><Input label="Nome" value={invite.name} onChange={value => setInvite({ ...invite, name: value })} required /><Input label="E-mail" type="email" value={invite.email} onChange={value => setInvite({ ...invite, email: value })} required /><label className="text-sm font-medium">Papel<select value={invite.role} onChange={event => setInvite({ ...invite, role: event.target.value as 'secretary' | 'professional' })} className={inputStyle}><option value="secretary">Secretária</option><option value="professional">Profissional</option></select></label><Input label="Senha temporária" type="password" value={invite.temporaryPassword} onChange={value => setInvite({ ...invite, temporaryPassword: value })} required />{invite.role === 'professional' && <Input label="Especialidade" value={invite.specialty} onChange={value => setInvite({ ...invite, specialty: value })} />}<button disabled={inviteMutation.isPending} className={`sm:col-span-2 ${buttonStyle}`}><MailPlus size={17} />{inviteMutation.isPending ? 'Criando…' : 'Criar acesso'}</button></form><MemberList items={members.data ?? []} onToggle={(item) => toggleMember.mutate({ id: item.id, active: !item.active })} /></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><Title icon={<BriefcaseMedical />} title="Profissionais" text="Cadastre profissionais mesmo que eles não precisem acessar o painel." /><form onSubmit={event => submit(event, professionalMutation.mutate)} className="mt-5 flex flex-col gap-3 sm:flex-row"><Input label="Nome" value={professional.name} onChange={value => setProfessional({ ...professional, name: value })} required /><Input label="Especialidade" value={professional.specialty} onChange={value => setProfessional({ ...professional, specialty: value })} /><button disabled={professionalMutation.isPending} className={`${buttonStyle} sm:self-end`}><UserRoundPlus size={17} />Adicionar</button></form><SimpleList empty="Nenhum profissional cadastrado." items={professionals.data ?? []} render={item => <><span><strong>{item.name}</strong>{item.specialty && <small> | {item.specialty}</small>}</span><Toggle active={item.active} onClick={() => toggleProfessional.mutate({ id: item.id, active: !item.active })} /></>} /></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm xl:col-span-2"><Title icon={<DoorOpen />} title="Salas e cadeiras" text="Cadastre recursos para distribuir os atendimentos." /><form onSubmit={event => submit(event, resourceMutation.mutate)} className="mt-5 grid gap-3 sm:grid-cols-[1fr_180px_auto]"><Input label="Nome do recurso" value={resource.name} onChange={value => setResource({ ...resource, name: value })} required /><Input label="Tipo" value={resource.resourceType} onChange={value => setResource({ ...resource, resourceType: value })} required /><button disabled={resourceMutation.isPending} className={`${buttonStyle} sm:self-end`}><Armchair size={17} />Adicionar</button></form><SimpleList empty="Nenhuma sala ou cadeira cadastrada." items={resources.data ?? []} render={item => <><span><strong>{item.name}</strong><small> | {item.resource_type}</small></span><Toggle active={item.active} onClick={() => toggleResource.mutate({ id: item.id, active: !item.active })} /></>} /></div>
    {notice && <p className={`xl:col-span-2 rounded-lg p-3 text-sm ${notice.startsWith('Erro:') ? 'bg-red-50 text-red-700' : 'bg-vita-50 text-vita-700'}`}>{notice}</p>}
  </section>
}

const inputStyle = 'mt-1.5 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 outline-none focus:border-vita-600'
const buttonStyle = 'inline-flex items-center justify-center gap-2 rounded-lg bg-vita-600 px-4 py-2.5 font-semibold text-white hover:bg-vita-700 disabled:opacity-60'
function Title({ icon, title, text }: { icon: React.ReactNode, title: string, text: string }) { return <div className="flex gap-3"><div className="text-vita-600">{icon}</div><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm text-slate-600">{text}</p></div></div> }
function Input({ label, value, onChange, type = 'text', required = false }: { label: string, value: string, onChange: (value: string) => void, type?: string, required?: boolean }) { return <label className="text-sm font-medium">{label}<input type={type} value={value} onChange={event => onChange(event.target.value)} required={required} className={inputStyle} /></label> }
function MemberList({ items, onToggle }: { items: OrganizationMember[], onToggle: (item: OrganizationMember) => void }) { return <SimpleList empty="Nenhum usuário com acesso." items={items} render={item => <><span><strong>{item.profiles?.full_name || item.profiles?.email || 'Usuário'}</strong><small> | {roleLabel(item.role)}{item.profiles?.email && ` | ${item.profiles.email}`}</small></span>{item.role === 'owner' ? <small className="font-medium text-slate-500">Dono</small> : <Toggle active={item.active} onClick={() => onToggle(item)} />}</>} /> }
function SimpleList<T extends { id: number, active: boolean }>({ items, empty, render }: { items: T[], empty: string, render: (item: T) => React.ReactNode }) { return <div className="mt-5 divide-y divide-slate-100">{items.map(item => <div key={item.id} className="flex items-center justify-between gap-4 py-3 text-sm">{render(item)}</div>)}{!items.length && <p className="py-5 text-sm text-slate-500">{empty}</p>}</div> }
function Toggle({ active, onClick }: { active: boolean, onClick: () => void }) { return <button onClick={onClick} className={`rounded-full px-2.5 py-1 text-xs font-semibold ${active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{active ? 'Ativo' : 'Inativo'}</button> }
function roleLabel(role: OrganizationMember['role']) { return ({ owner: 'Dono', manager: 'Gestor', secretary: 'Secretária', professional: 'Profissional' })[role] }
function translateError(message: string) { if (message.includes('User already registered')) return 'já existe um usuário com este e-mail.'; if (message === 'invalid_member_data') return 'preencha os dados e use uma senha de ao menos 8 caracteres.'; if (message === 'owner_membership_cannot_be_changed') return 'o acesso do dono não pode ser desativado por aqui.'; return message }
