import { useMemo, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Pencil, Search, Trash2, UserPlus, UsersRound, X } from 'lucide-react'
import { deletePatient, listPatients, savePatient, type Patient, type PatientInput } from '../lib/patients'

const emptyPatient: PatientInput = { name: '', phone: '', email: '', address: '', birthDate: '' }
export function PatientsSection({ clinicId, enabled }: { clinicId: number, enabled: boolean }) {
  const client = useQueryClient()
  const [form, setForm] = useState<PatientInput>(emptyPatient)
  const [query, setQuery] = useState('')
  const [notice, setNotice] = useState('')
  const patients = useQuery({ queryKey: ['patients', clinicId], queryFn: () => listPatients(clinicId), enabled })
  const refresh = () => client.invalidateQueries({ queryKey: ['patients', clinicId] })
  const save = useMutation({ mutationFn: () => savePatient(clinicId, form), onSuccess: () => { setForm(emptyPatient); setNotice('Paciente salvo com sucesso.'); refresh() }, onError: (error: Error) => setNotice(`Erro: ${translateError(error.message)}`) })
  const remove = useMutation({ mutationFn: deletePatient, onSuccess: () => { setNotice('Paciente excluído.'); refresh() }, onError: (error: Error) => setNotice(`Erro: ${translateError(error.message)}`) })
  const filtered = useMemo(() => (patients.data ?? []).filter(patient => `${patient.name} ${patient.phone} ${patient.email ?? ''}`.toLowerCase().includes(query.toLowerCase())), [patients.data, query])
  if (!enabled) return null
  const submit = (event: FormEvent) => { event.preventDefault(); setNotice(''); save.mutate() }
  const edit = (patient: Patient) => { setForm({ id: patient.id, name: patient.name, phone: patient.phone, email: patient.email ?? '', address: patient.address ?? '', birthDate: patient.birth_date ?? '' }); window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' }) }
  return <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div className="flex gap-3"><div className="text-vita-600"><UsersRound /></div><div><h2 className="font-bold">Pacientes</h2><p className="mt-1 text-sm text-slate-600">Cadastre e mantenha os dados dos pacientes da organização.</p></div></div><div className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar paciente" className="rounded-lg border border-slate-300 py-2 pl-9 pr-3 text-sm outline-none focus:border-vita-600" /></div></div>
    <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Paciente</th><th className="px-4 py-3">Telefone</th><th className="px-4 py-3">Data de nascimento</th><th className="px-4 py-3">E-mail</th><th className="px-4 py-3 text-right">Ações</th></tr></thead><tbody>{filtered.map(patient => <tr key={patient.id} className="border-b border-slate-100"><td className="px-4 py-3"><strong>{patient.name}</strong>{patient.address && <small> | {patient.address}</small>}</td><td className="px-4 py-3">{patient.phone}</td><td className="px-4 py-3">{patient.birth_date ? formatDate(patient.birth_date) : '—'}</td><td className="px-4 py-3">{patient.email ?? '—'}</td><td className="px-4 py-3"><div className="flex justify-end gap-2"><IconButton label="Editar" onClick={() => edit(patient)}><Pencil size={16} /></IconButton><IconButton label="Excluir" onClick={() => { if (window.confirm(`Excluir ${patient.name}?`)) remove.mutate(patient.id) }}><Trash2 size={16} /></IconButton></div></td></tr>)}{!filtered.length && <tr><td colSpan={5} className="px-4 py-8 text-center text-slate-500">{patients.isLoading ? 'Carregando pacientes…' : 'Nenhum paciente encontrado.'}</td></tr>}</tbody></table></div>
    <form onSubmit={submit} className="mt-6 border-t border-slate-200 pt-6"><div className="flex items-center justify-between"><div><h3 className="font-semibold">{form.id ? 'Editar paciente' : 'Novo paciente'}</h3><p className="mt-1 text-sm text-slate-600">Telefone é o identificador do paciente nesta organização.</p></div>{form.id && <button type="button" onClick={() => setForm(emptyPatient)} className="inline-flex items-center gap-1 text-sm text-slate-600 hover:text-slate-950"><X size={16} />Cancelar</button>}</div><div className="mt-4 grid gap-3 md:grid-cols-2"><Input label="Nome" value={form.name} onChange={value => setForm({ ...form, name: value })} required /><Input label="Telefone" value={form.phone} onChange={value => setForm({ ...form, phone: value })} required /><Input label="Data de nascimento" type="date" value={form.birthDate} onChange={value => setForm({ ...form, birthDate: value })} /><Input label="E-mail" type="email" value={form.email} onChange={value => setForm({ ...form, email: value })} /><Input label="Endereço" value={form.address} onChange={value => setForm({ ...form, address: value })} /><button disabled={save.isPending} className="inline-flex items-center justify-center gap-2 rounded-lg bg-vita-600 px-4 py-2.5 font-semibold text-white hover:bg-vita-700 disabled:opacity-60 md:col-span-2"><UserPlus size={17} />{save.isPending ? 'Salvando…' : form.id ? 'Salvar alterações' : 'Cadastrar paciente'}</button></div></form>{notice && <p className={`mt-4 rounded-lg p-3 text-sm ${notice.startsWith('Erro:') ? 'bg-red-50 text-red-700' : 'bg-vita-50 text-vita-700'}`}>{notice}</p>}
  </section>
}
function Input({ label, value, onChange, type = 'text', required = false }: { label: string, value: string, onChange: (value: string) => void, type?: string, required?: boolean }) { return <label className="text-sm font-medium">{label}<input type={type} value={value} onChange={event => onChange(event.target.value)} required={required} className="mt-1.5 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 outline-none focus:border-vita-600" /></label> }
function IconButton({ label, onClick, children }: { label: string, onClick: () => void, children: React.ReactNode }) { return <button type="button" title={label} aria-label={label} onClick={onClick} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100 hover:text-vita-700">{children}</button> }
function translateError(message: string) { if (message.includes('duplicate key')) return 'já existe um paciente com este telefone.'; if (message.includes('violates foreign key')) return 'este paciente possui agendamentos e não pode ser excluído.'; return message }
function formatDate(value: string) { const [year, month, day] = value.slice(0, 10).split('-'); return `${day}/${month}/${year}` }
