import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CalendarClock, Clock3, Plus, Trash2 } from 'lucide-react'
import { createAppointmentType, createWorkingHour, deleteAppointmentType, deleteWorkingHour, listAppointmentTypes, listWorkingHours, setAppointmentTypeActive, type AppointmentType } from '../lib/scheduleSettings'
import { listProfessionals } from '../lib/organizationTeam'

const weekdays = ['Domingo', 'Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado']

export function ScheduleSettingsSection({ clinicId, enabled }: { clinicId: number, enabled: boolean }) {
  const client = useQueryClient()
  const [notice, setNotice] = useState('')
  const [appointment, setAppointment] = useState({ professionalId: '', duration: '30', interval: '0' })
  const [workingHour, setWorkingHour] = useState({ professionalId: '', weekdays: [1], startTime: '09:00', endTime: '18:00' })
  const types = useQuery({ queryKey: ['appointment-types', clinicId], queryFn: () => listAppointmentTypes(clinicId), enabled })
  const hours = useQuery({ queryKey: ['working-hours', clinicId], queryFn: () => listWorkingHours(clinicId), enabled })
  const professionals = useQuery({ queryKey: ['professionals', clinicId], queryFn: () => listProfessionals(clinicId), enabled })
  if (!enabled) return null
  const refresh = () => { client.invalidateQueries({ queryKey: ['appointment-types', clinicId] }); client.invalidateQueries({ queryKey: ['working-hours', clinicId] }) }
  const reportError = (error: Error) => setNotice(`Erro: ${error.message}`)
  const addType = useMutation({ mutationFn: () => { const professional = (professionals.data ?? []).find(item => item.id === Number(appointment.professionalId)); if (!professional) throw new Error('Selecione um profissional.'); return createAppointmentType(clinicId, { professionalId: professional.id, name: professional.name, duration: Number(appointment.duration), interval: Number(appointment.interval) }) }, onSuccess: () => { setAppointment({ professionalId: '', duration: '30', interval: '0' }); setNotice('Configuração de consulta cadastrada.'); refresh() }, onError: reportError })
  const toggleType = useMutation({ mutationFn: ({ id, active }: { id: number, active: boolean }) => setAppointmentTypeActive(id, active), onSuccess: refresh, onError: reportError })
  const removeType = useMutation({ mutationFn: deleteAppointmentType, onSuccess: refresh, onError: reportError })
  const addHour = useMutation({ mutationFn: () => { if (!workingHour.weekdays.length) throw new Error('Selecione ao menos um dia da semana.'); return Promise.all(workingHour.weekdays.map(weekday => createWorkingHour(clinicId, { professionalId: workingHour.professionalId ? Number(workingHour.professionalId) : null, weekday, startTime: workingHour.startTime, endTime: workingHour.endTime }))) }, onSuccess: () => { setNotice('Horário de atendimento cadastrado.'); refresh() }, onError: reportError })
  const removeHour = useMutation({ mutationFn: deleteWorkingHour, onSuccess: refresh, onError: reportError })
  const submit = (event: FormEvent, action: () => void) => { event.preventDefault(); setNotice(''); action() }
  return <section className="mt-8 grid gap-6 xl:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><Title icon={<Clock3 />} title="Tipos de consulta" text="A duração e o intervalo entram no cálculo dos horários disponíveis." /><form onSubmit={event => submit(event, addType.mutate)} className="mt-5 grid gap-3 sm:grid-cols-[1fr_120px_120px_auto]"><label className="text-sm font-medium">Nome<select value={appointment.professionalId} onChange={event => setAppointment({ ...appointment, professionalId: event.target.value })} required className={inputStyle}><option value="">Selecione o profissional</option>{(professionals.data ?? []).filter(item => item.active).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><NumberInput label="Duração (min)" value={appointment.duration} onChange={value => setAppointment({ ...appointment, duration: value })} min={5} max={480} /><NumberInput label="Intervalo (min)" value={appointment.interval} onChange={value => setAppointment({ ...appointment, interval: value })} min={0} max={240} /><button disabled={addType.isPending} className={`${buttonStyle} sm:self-end`}><Plus size={17} />Adicionar</button></form><div className="mt-5 divide-y divide-slate-100">{(types.data ?? []).map(item => <div key={item.id} className="flex items-center justify-between gap-3 py-3 text-sm"><span><strong>{item.professionals?.name ?? item.name}</strong><small> | {item.duration_minutes} min · intervalo de {item.interval_minutes} min</small></span><div className="flex items-center gap-2"><Toggle active={item.active} onClick={() => toggleType.mutate({ id: item.id, active: !item.active })} /><DeleteButton onClick={() => removeType.mutate(item.id)} /></div></div>)}{!types.data?.length && <p className="py-5 text-sm text-slate-500">Nenhuma configuração de consulta cadastrada.</p>}</div></article>
    <article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><Title icon={<CalendarClock />} title="Horários de atendimento" text="Defina um horário geral ou específico para cada profissional." /><form onSubmit={event => submit(event, addHour.mutate)} className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Aplicar a<select value={workingHour.professionalId} onChange={event => setWorkingHour({ ...workingHour, professionalId: event.target.value })} className={inputStyle}><option value="">Organização inteira</option>{(professionals.data ?? []).filter(item => item.active).map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><fieldset className="text-sm font-medium"><legend>Dias da semana</legend><div className="mt-1.5 flex flex-wrap gap-x-3 gap-y-2 rounded-lg border border-slate-300 p-3">{weekdays.map((day, index) => <label key={day} className="flex items-center gap-1.5 text-xs font-normal"><input type="checkbox" checked={workingHour.weekdays.includes(index)} onChange={() => setWorkingHour({ ...workingHour, weekdays: workingHour.weekdays.includes(index) ? workingHour.weekdays.filter(item => item !== index) : [...workingHour.weekdays, index].sort((a, b) => a - b) })} />{day.replace('-feira', '')}</label>)}</div></fieldset><TimeInput label="Início" value={workingHour.startTime} onChange={value => setWorkingHour({ ...workingHour, startTime: value })} /><TimeInput label="Fim" value={workingHour.endTime} onChange={value => setWorkingHour({ ...workingHour, endTime: value })} /><button disabled={addHour.isPending} className={`sm:col-span-2 ${buttonStyle}`}><Plus size={17} />Adicionar horário aos dias selecionados</button></form><div className="mt-5 divide-y divide-slate-100">{(hours.data ?? []).map(item => <div key={item.id} className="flex items-center justify-between gap-3 py-3 text-sm"><span><strong>{weekdays[item.weekday]}</strong><small> | {item.professionals?.name ?? 'Organização inteira'} · {formatTime(item.start_time)}–{formatTime(item.end_time)}</small></span><DeleteButton onClick={() => removeHour.mutate(item.id)} /></div>)}{!hours.data?.length && <p className="py-5 text-sm text-slate-500">Nenhum horário de atendimento cadastrado.</p>}</div></article>
    {notice && <p className={`xl:col-span-2 rounded-lg p-3 text-sm ${notice.startsWith('Erro:') ? 'bg-red-50 text-red-700' : 'bg-vita-50 text-vita-700'}`}>{notice}</p>}
  </section>
}
const inputStyle = 'mt-1.5 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 outline-none focus:border-vita-600'
const buttonStyle = 'inline-flex items-center justify-center gap-2 rounded-lg bg-vita-600 px-4 py-2.5 font-semibold text-white hover:bg-vita-700 disabled:opacity-60'
function Title({ icon, title, text }: { icon: React.ReactNode, title: string, text: string }) { return <div className="flex gap-3"><div className="text-vita-600">{icon}</div><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm text-slate-600">{text}</p></div></div> }
function Input({ label, value, onChange, required = false }: { label: string, value: string, onChange: (value: string) => void, required?: boolean }) { return <label className="text-sm font-medium">{label}<input value={value} onChange={event => onChange(event.target.value)} required={required} className={inputStyle} /></label> }
function NumberInput({ label, value, onChange, min, max }: { label: string, value: string, onChange: (value: string) => void, min: number, max: number }) { return <label className="text-sm font-medium">{label}<input type="number" value={value} onChange={event => onChange(event.target.value)} min={min} max={max} required className={inputStyle} /></label> }
function TimeInput({ label, value, onChange }: { label: string, value: string, onChange: (value: string) => void }) { return <label className="text-sm font-medium">{label}<input type="time" value={value} onChange={event => onChange(event.target.value)} required className={inputStyle} /></label> }
function Toggle({ active, onClick }: { active: boolean, onClick: () => void }) { return <button onClick={onClick} className={`rounded-full px-2.5 py-1 text-xs font-semibold ${active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{active ? 'Ativo' : 'Inativo'}</button> }
function DeleteButton({ onClick }: { onClick: () => void }) { return <button onClick={onClick} title="Excluir" aria-label="Excluir" className="rounded-lg p-2 text-slate-500 hover:bg-red-50 hover:text-red-700"><Trash2 size={16} /></button> }
function formatTime(time: string) { return time.slice(0, 5) }
